package seniordesign;


import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.regex.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iamjong
 */
public class Home_Page extends javax.swing.JFrame {

    public static AdvisingDB db;
    public static int advisorID = 0;
    
    public Home_Page() {
        initComponents();
        this.setLocationRelativeTo(null);
        studentIDText.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SearchButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        studentIDText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CatalogButton = new javax.swing.JButton();
        NewAdvisor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 14, 39));

        jPanel1.setBackground(new java.awt.Color(236, 168, 31));
        jPanel1.setForeground(new java.awt.Color(236, 168, 31));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("COMPUTER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jPanel2.setBackground(new java.awt.Color(100, 14, 39));

        SearchButton.setBackground(new java.awt.Color(100, 14, 39));
        SearchButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        SearchButton.setForeground(new java.awt.Color(234, 181, 67));
        SearchButton.setText("SEARCH");
        SearchButton.setMaximumSize(new java.awt.Dimension(85, 30));
        SearchButton.setMinimumSize(new java.awt.Dimension(85, 30));
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(100, 14, 39));
        ExitButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(234, 181, 67));
        ExitButton.setText("LOGOUT");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        studentIDText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentIDTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                studentIDTextFocusLost(evt);
            }
        });
        studentIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDTextActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student ID #:");

        CatalogButton.setBackground(new java.awt.Color(100, 14, 39));
        CatalogButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        CatalogButton.setForeground(new java.awt.Color(234, 181, 67));
        CatalogButton.setText("CATALOG");
        CatalogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatalogButtonActionPerformed(evt);
            }
        });

        NewAdvisor.setBackground(new java.awt.Color(100, 14, 39));
        NewAdvisor.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        NewAdvisor.setForeground(new java.awt.Color(234, 181, 67));
        NewAdvisor.setText("New Advisor");
        NewAdvisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAdvisorActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(236, 168, 31));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 168, 31));
        jLabel2.setText("SCIENCE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentIDText)
                    .addComponent(SearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CatalogButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewAdvisor))
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CatalogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewAdvisor, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
       //db.deleteUser();
       AdvisorForm advisor = new AdvisorForm();
       
       int studentID = 0;
       
       String Id_pattern = "^[a-zA-Z0]";
       if(studentIDText.getText().equals("") || Pattern.matches(Id_pattern, studentIDText.getText()))
       {
            System.out.println("Invalid input");
            JOptionPane.showMessageDialog(null, "Invalid ID or Input!", "Error", JOptionPane.ERROR_MESSAGE);

       }
       else
       {
            studentID = Integer.parseInt(studentIDText.getText());
            advisor.getCourses();
            advisor.displayInfo(studentID,advisorID);
            advisor.setVisible(true);
            this.dispose();
       }
       
       
       
       
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        Log_in login = new Log_in();
        login.setVisible(true);
        this.dispose();
        //System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void studentIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDTextActionPerformed

    private void studentIDTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIDTextFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_studentIDTextFocusLost

    private void studentIDTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIDTextFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_studentIDTextFocusGained

    private void CatalogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatalogButtonActionPerformed
        // TODO add your handling code here:
        Catalogs cat = new Catalogs();
        cat.getCourses();
        cat.setVisible(true);
        
    }//GEN-LAST:event_CatalogButtonActionPerformed

    private void NewAdvisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAdvisorActionPerformed
        // TODO add your handling code here:
        advisorRegistration aR = new advisorRegistration();
        aR.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_NewAdvisorActionPerformed
    public void advisorInfo(int id)
    {
        advisorID = id;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        db = new AdvisingDB();
        //
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_Page().setVisible(true);
                new Home_Page().setResizable(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CatalogButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton NewAdvisor;
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField studentIDText;
    // End of variables declaration//GEN-END:variables
}
