package seniordesign;

import java.util.Random;
import java.util.regex.*;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class RegistrationForm extends javax.swing.JFrame {
    private static boolean confirmed = false;
    Random rnd = new Random();
    /**
     * Creates new form RegistrationForm
     */
    public RegistrationForm() {
        initComponents();
    }
    public void confirmEmail()
    {
        
        System.out.println("Confirmed");
        
        AdvisingDB reg = new AdvisingDB();
        String major = jComboBoxMajor.getSelectedItem().toString();
        reg.addUser(Integer.parseInt(StudentIDTextField.getText()),FirstNameField.getText(),LastNameField.getText(), ConfirmEmailTextField.getText(), major);
        //register (username,pass,isAdv,sID,aID)
        reg.register(UsernameTextField.getText(), PasswordTextField.getText(),false,Integer.parseInt(StudentIDTextField.getText()),0);
        /////////////////
        
        JOptionPane.showMessageDialog(null, "Thank You for Registering", "Welcome", JOptionPane.PLAIN_MESSAGE);
        
        Log_in lgi = new Log_in();
        lgi.setVisible(true);
        this.dispose();
            
            
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        UsernameLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        LastNameField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        UsernameTextField = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        ConfirmEmailLabel1 = new javax.swing.JLabel();
        ConfirmEmailTextField = new javax.swing.JTextField();
        ConfirmPasswordLabel = new javax.swing.JLabel();
        EmailVerificationLabel = new javax.swing.JLabel();
        ConEmailVerificationLabel = new javax.swing.JLabel();
        ConPassVerificationLabel = new javax.swing.JLabel();
        ConfirmPassworTextField = new javax.swing.JPasswordField();
        PasswordTextField = new javax.swing.JPasswordField();
        StudentIDTextField = new javax.swing.JTextField();
        StudentIDLabel = new javax.swing.JLabel();
        MajorLabel = new javax.swing.JLabel();
        jComboBoxMajor = new javax.swing.JComboBox<>();
        PasswordMatchLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(234, 181, 67));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Register");

        jPanel2.setBackground(new java.awt.Color(100, 14, 39));

        FirstNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        FirstNameLabel.setForeground(new java.awt.Color(234, 181, 67));
        FirstNameLabel.setText("First Name:");

        LastNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        LastNameLabel.setForeground(new java.awt.Color(234, 181, 67));
        LastNameLabel.setText("Last Name:");

        EmailLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(234, 181, 67));
        EmailLabel.setText("Email:");

        UsernameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        UsernameLabel.setForeground(new java.awt.Color(234, 181, 67));
        UsernameLabel.setText("Username:");

        PasswordLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        PasswordLabel.setForeground(new java.awt.Color(234, 181, 67));
        PasswordLabel.setText("Password:");

        LastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameFieldActionPerformed(evt);
            }
        });

        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });
        EmailTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailTextFieldKeyReleased(evt);
            }
        });

        UsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameTextFieldActionPerformed(evt);
            }
        });

        RegisterButton.setBackground(new java.awt.Color(100, 14, 39));
        RegisterButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(234, 181, 67));
        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        jButtonCancel.setBackground(new java.awt.Color(100, 14, 39));
        jButtonCancel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(234, 181, 67));
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        ConfirmEmailLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ConfirmEmailLabel1.setForeground(new java.awt.Color(234, 181, 67));
        ConfirmEmailLabel1.setText("Confirm Email:");

        ConfirmEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmEmailTextFieldActionPerformed(evt);
            }
        });

        ConfirmPasswordLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        ConfirmPasswordLabel.setForeground(new java.awt.Color(234, 181, 67));
        ConfirmPasswordLabel.setText("Confirm Password:");

        EmailVerificationLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailVerificationLabel.setText("@toromail.csudh.edu");

        ConEmailVerificationLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConEmailVerificationLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ConEmailVerificationLabelKeyReleased(evt);
            }
        });

        ConPassVerificationLabel.setForeground(new java.awt.Color(255, 255, 255));

        ConfirmPassworTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmPassworTextFieldActionPerformed(evt);
            }
        });

        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });

        StudentIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDTextFieldActionPerformed(evt);
            }
        });

        StudentIDLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        StudentIDLabel.setForeground(new java.awt.Color(234, 181, 67));
        StudentIDLabel.setText("Student ID:");

        MajorLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        MajorLabel.setForeground(new java.awt.Color(234, 181, 67));
        MajorLabel.setText("Major:");

        jComboBoxMajor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science", "Mathematics", "Physics" }));
        jComboBoxMajor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMajorActionPerformed(evt);
            }
        });

        PasswordMatchLabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RegisterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(FirstNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(LastNameLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(ConfirmEmailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                            .addComponent(ConfirmEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(UsernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(EmailLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(ConfirmPasswordLabel)
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(PasswordLabel)
                                    .addGap(71, 71, 71)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ConfirmPassworTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(PasswordTextField)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StudentIDLabel)
                                .addComponent(MajorLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(StudentIDTextField)
                                .addComponent(jComboBoxMajor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ConPassVerificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConEmailVerificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailVerificationLabel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PasswordMatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentIDLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MajorLabel)
                    .addComponent(jComboBoxMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailLabel)
                            .addComponent(EmailVerificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ConfirmEmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ConfirmEmailLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ConEmailVerificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsernameLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordMatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PasswordLabel)
                        .addComponent(PasswordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ConPassVerificationLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ConfirmPasswordLabel)
                        .addComponent(ConfirmPassworTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegisterButton)
                    .addComponent(jButtonCancel))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameFieldActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        Log_in lgi = new Log_in();
        lgi.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
        boolean emailConfirm = true;
        boolean passConfirm = false;
        /*
        //check if email matches to check for misspelled email
        String email_Pattern = "^[a-zA-Z0-9]{1,20}@[a-zA-Z]{6,9}.[a-zA-Z]{4,6}.[a-zA-Z0-9]{2,3}";
        //Pattern.matches(EmailTextField.getText()
        if(!(Pattern.matches(email_Pattern, EmailTextField.getText())))
        {
            EmailVerificationLabel.setText("Invalid");
            
        }
        else{
            
            EmailVerificationLabel.setText("Verified");
            
            if(!(Pattern.matches(EmailTextField.getText(), ConfirmEmailTextField.getText())))
            {
                ConEmailVerificationLabel.setText("does not match");
            }
            else
            {
                ConEmailVerificationLabel.setText("Verified");
                emailConfirm = true;
            }
        }
        */
        String pass_Pattern = "^[a-zA-Z0-9]{5,20}"; //at least 5 character a-z and 0-9
        if(!(Pattern.matches(pass_Pattern, PasswordTextField.getText())))
        {
            PasswordMatchLabel.setText("at least 5 characters");
        }
        else
        {
            PasswordMatchLabel.setText("Verified");
            
            //check if password matches to check for misspelled password
            if(!(Pattern.matches(PasswordTextField.getText(), ConfirmPassworTextField.getText())))
            {
                ConPassVerificationLabel.setText("does not match");
            }
            else{

                ConPassVerificationLabel.setText(null);
                passConfirm = true;
            }
        }
        
        //proceed to register new student
        if(emailConfirm == true && passConfirm == true)
        {
            //Send confirmation CODE to email provided
            System.out.println("Send Email");
            SendMail sendEmail = new SendMail();
            
            String Subject = "Email Authentication";
            int rndCode = rnd.nextInt(999999) + 200000;
            String Text = "Enter this Code: " + rndCode + " to verify email \n This code will expire in 15 minutes";
            //Send email//emailRecipent, Subj, Text
            sendEmail.sendMail(ConfirmEmailTextField.getText(),Subject,Text);
            System.out.println("email sent");
            //create new frame with input for code
            //verify code and return true
            //continue with registration
            //
            //needs to check for unique student ID else cannor add
            System.out.println("verifyEmail");
            verifyEmail verify = new verifyEmail();
            verify.verify(this, ConfirmEmailTextField.getText(), rndCode);
            verify.setVisible(true);
            
            //////////////////
            /*
            if(confirmed == true)
            {
                System.out.println("Confirmed");

                AdvisingDB reg = new AdvisingDB();
                String major = jComboBoxMajor.getSelectedItem().toString();
                reg.addUser(Integer.parseInt(StudentIDTextField.getText()),FirstNameField.getText(),LastNameField.getText(), ConfirmEmailTextField.getText(), major);
                //register (username,pass,isAdv,sID,aID)
                reg.register(UsernameTextField.getText(), PasswordTextField.getText(),false,Integer.parseInt(StudentIDTextField.getText()),0);
                /////////////////


                JOptionPane.showMessageDialog(null, "Thank You for Registering", "Welcome", JOptionPane.PLAIN_MESSAGE);

                Log_in lgi = new Log_in();
                lgi.setVisible(true);
                this.dispose();
            }
            */
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Make sure all fields are correctly filled.", "Failure", JOptionPane.ERROR_MESSAGE);
        
        }
        
        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void EmailTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailTextFieldKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_EmailTextFieldKeyReleased

    private void ConfirmEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmEmailTextFieldActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ConfirmEmailTextFieldActionPerformed

    private void ConEmailVerificationLabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ConEmailVerificationLabelKeyReleased
        // TODO add your handling code here:
         
    }//GEN-LAST:event_ConEmailVerificationLabelKeyReleased

    private void UsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameTextFieldActionPerformed

    private void ConfirmPassworTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmPassworTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmPassworTextFieldActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void StudentIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIDTextFieldActionPerformed

    private void jComboBoxMajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMajorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMajorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConEmailVerificationLabel;
    private javax.swing.JLabel ConPassVerificationLabel;
    private javax.swing.JLabel ConfirmEmailLabel1;
    private javax.swing.JTextField ConfirmEmailTextField;
    private javax.swing.JPasswordField ConfirmPassworTextField;
    private javax.swing.JLabel ConfirmPasswordLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JLabel EmailVerificationLabel;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel MajorLabel;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JLabel PasswordMatchLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel StudentIDLabel;
    private javax.swing.JTextField StudentIDTextField;
    private javax.swing.JLabel UsernameLabel;
    private javax.swing.JTextField UsernameTextField;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox<String> jComboBoxMajor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables
}
